apiVersion: v2
name: snark-worker
description: A Helm chart for Mina Protocol's SNARK worker nodes
type: application
version: 0.4.4
appVersion: 1.16.0
dependencies:
  - name: common-utilities
    version: 0.0.7
    repository: "https://coda-charts.storage.googleapis.com"
icon: https://storage.googleapis.com/coda-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- snarks
- zero-knowledge
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina/tree/develop/src/lib/snark_worker
