apiVersion: v2
name: leaderboard
description: A Helm chart for Coda Protocol's Testnet leaderboard service
type: application
version: 0.1.9
appVersion: 1.16.0
icon: https://storage.googleapis.com/coda-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- coda protocol
- testnet
- leaderboard
- points
- mina
- testnet
home: https://codaprotocol.com/
sources:
- https://github.com/CodaProtocol/coda/tree/develop/frontend/leaderboard
